//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSketch.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherStandardMapping
    {
        public long TeacherStandardId { get; set; }
        public long TeacherId { get; set; }
        public long StandardId { get; set; }
    
        public virtual StandardMaster StandardMaster { get; set; }
        public virtual TeacherMaster TeacherMaster { get; set; }
    }
}
